/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.bmuschko.a

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibraryASuite extends AnyFunSuite {
  test("someLibraryMethod is always true") {
    def library = new LibraryA()
    assert(library.fromProjectA())
  }
}
