/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.bmuschko.c

import com.bmuschko.a.LibraryA

class LibraryC {
  def fromProjectC(): Boolean = new LibraryA().fromProjectA()
}
