/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.bmuschko.e

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibraryESuite extends AnyFunSuite {
  test("someLibraryMethod is always true") {
    def library = new LibraryE()
    assert(library.fromProjectE())
  }
}
