/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.bmuschko.d

import org.apache.commons.lang3.StringUtils

class LibraryD {
  def fromProjectD(): Boolean = true
  def usage: String = StringUtils.upperCase("Hello World")
}
