/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.bmuschko.b

import com.bmuschko.a.LibraryA

class LibraryB {
  def fromProjectB(): Boolean = new LibraryA().fromProjectA()
}
