/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.bmuschko.c

import org.junit.runner.RunWith
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibraryCSuite extends AnyFunSuite {
  test("someLibraryMethod is always true") {
    def library = new LibraryC()
    assert(library.fromProjectC())
  }
}
